# The inputs, outputs, params, filename, and filepath
# of this task file are part of its semantically versioned API.
# See our documentation for a detailed discussion of our semver API.
# See www.semver.org for an explanation of semantic versioning.

# code_snippet creds-interpolate start yaml
---
platform: linux

inputs:
- name: config # contains the base configuration file
- name: vars # variable files to be made available
  optional: true

outputs:
- name: interpolated-files
#contains all the *.yml files from `files/` input but after interpolation

params:
  VARS_FILES:
  # - Optional
  # - Filepath to the Ops Manager vars yaml file
  # - The path is relative to root of the task build,
  #   so `vars` and `secrets` can be used.
  CONFIG_FILE: base.yml

run:
  path: bash
  args:
  - "-c"
  - |
    cat /var/version && echo ""
    set -eux

    vars_files_args=("")
    for vf in ${VARS_FILES}
    do
      vars_files_args+=("--vars-file ${vf}")
    done

    echo "this is new creds-interpolate"

    # ${vars_files_args[@] needs to be globbed to pass through properly
    # shellcheck disable=SC2068
    echo "getting config dirname:"
    dirname config
    echo "in memory interpolate"
    om interpolate --config "config/$CONFIG_FILE" ${vars_files_args[@]}
    echo "persistent interpolate"
    om interpolate --config "config/$CONFIG_FILE" ${vars_files_args[@]} --output-file interpolated-files/$CONFIG_FILE
# code_snippet creds-interpolate end
