# The inputs, outputs, params, filename, and filepath
# of this task file are part of its semantically versioned API.
# See our documentation for a detailed discussion of our semver API.
# See www.semver.org for an explanation of semantic versioning.

# code_snippet creds-interpolate start yaml
---
platform: linux

inputs:
- name: config # contains the base configuration file
- name: secrets # variable files to be made available
  optional: true

params:
  SECRETS_FILE:

outputs:
- name: interpolated-files
#contains all the *.yml files from `files/` input but after interpolation

run:
  path: bash
  args:
  - "-c"
  - |
    cat /var/version && echo ""
    set -eux


    product_version=$(om interpolate \
      --config ${SECRETS_FILE} \
      --path /ops_files)

    echo "product_version"
    echo $product_version

    OPS_FILES=$(om interpolate \
      --config ${SECRETS_FILE} \
      --path /ops_files)

    echo "OPS_FILES"
    echo $OPS_FILES

    ops_files_args=("")
    for of in ${OPS_FILES}
    do
      ops_files_args+=("-o ${of}")
    done

    echo "ops_files_args"
    echo $ops_files_args
# code_snippet creds-interpolate end
