resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tags: latest-final

resources:
- name: pcf-automation
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: platform-automation

- name: configuration
  type: git
  source:
    uri: git@github.com:msathe-tech/platform-automation.git
    private_key: {{git_private_key}}

- name: credentials
  type: git
  source:
    uri: git@github.com:msathe-tech/platform-automation-private.git
    private_key: {{git_private_key}}

jobs:
- name: mysql
  serial: true
  plan:
  - aggregate:
    - get: configuration
      trigger: true
      params:
        unpack: true
    - get: pcf-automation-image
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*image*"]
    - get: pcf-automation-tasks
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*tasks*"]
    - get: credentials
      params:
        unpack: true

  - task: creds-interpolate
    image: pcf-automation-image
    file: configuration/fixes/tasks/creds-interpolate.yml
    input_mapping:
      config: configuration
      vars: credentials
    params:
      VARS_FILES: vars/creds-toolsmiths-pas.yml
      CONFIG_FILE: ((foundation))/config/templates/env.yml
    output_mapping:
      interpolated-files: configuration

  - task: configure-mysql
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: configuration
      env: configuration
      vars: configuration
    params:
      CONFIG_FILE: ((foundation))/config/templates/mysql.yml
      VARS_FILES: config/((foundation))/config/defaults/mysql.yml vars/((foundation))/config/vars/mysql.yml
      ENV_FILE: ((foundation))/config/templates/env.yml

- name: apply-mysql-changes
  serial: true
  plan:
  - aggregate:
    - get: configuration
      trigger: true
      passed: [ mysql ]
      params:
        unpack: true
    - get: pcf-automation-image
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*image*"]
    - get: pcf-automation-tasks
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*tasks*"]

  - task: apply-product-changes
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/apply-changes.yml
    input_mapping:
      env: configuration
    params:
      ENV_FILE: ((foundation))/config/templates/env.yml
