resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tags: latest-final

resources:
- name: pcf-automation
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: platform-automation

- name: configuration
  type: git
  source:
    uri: git@github.com:msathe-tech/platform-automation.git
    private_key: {{git_private_key}}

- name: credentials
  type: git
  source:
    uri: git@github.com:msathe-tech/platform-automation-private.git
    private_key: {{git_private_key}}

- name: tcg-config 
  type: git 
  source: 
    uri: https://github.com/DaxterM/tile-configuration.git 

jobs:
- name: ((pivnet-product-slug))
  serial: true
  plan:
  - aggregate:
    - get: configuration
      trigger: true
      params:
        unpack: true
    - get: tcg-config 
      params:
        unpack: true
    - get: pcf-automation-image
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*image*"]
    - get: pcf-automation-tasks
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*tasks*"]
    - get: credentials
      params:
        unpack: true

  - task: creds-interpolate
    image: pcf-automation-image
    file: configuration/fixes/tasks/creds-interpolate.yml
    input_mapping:
      config: configuration
      vars: credentials
    params:
      VARS_FILES: vars/creds-toolsmiths-pas.yml
      CONFIG_FILE: ((foundation))/config/templates/env.yml
    output_mapping:
      interpolated-files: configuration

  - task: tileconfig-((pivnet-product-slug))
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: tcg-config
      env: configuration
      vars: tcg-config
      secrets: credentials
    params:
      CONFIG_FILE: ((pivnet-product-slug))/((product-version))/product.yml
      OPS_FILES: ((ops_files))
      VARS_FILES: vars/((pivnet-product-slug))/((product-version))/product-default-vars.yml vars/((pivnet-product-slug))/((product-version))/resource-vars.yml vars/((pivnet-product-slug))/((product-version))/errand-vars.yml secrets/creds-toolsmiths-pas.yml
      ENV_FILE: ((foundation))/config/templates/env.yml
